export const LOADING_PLAYERS = 'LOADING_PLAYERS';
export const ADD_PLAYERS = 'ADD_PLAYERS';

export const LOADING_FIXTURE_DIFFICULTY = 'LOADING_FIXTURE_DIFFICULTY';
export const ADD_FIXTURE_DIFFICULTY = 'ADD_FIXTURE_DIFFICULTY';

export const LOADING_FIXTURE_LIST = 'LOADING_FIXTURE_LIST';
export const ADD_FIXTURE_LIST = 'ADD_FIXTURE_LIST';

export const LOADING_TEAM_IDS = 'LOADING_TEAM_IDS';
export const ADD_TEAM_IDS = 'ADD_TEAM_IDS';

export const LOADING_TEAMS_STATS = 'LOADING_TEAMS_STATS';
export const ADD_TEAMS_STATS = 'ADD_TEAMS_STATS';

export const LOADING_TEAM_FIXTURE_LIST = 'LOADING_TEAM_FIXTURE_LIST';
export const ADD_TEAM_FIXTURE_LIST = 'ADD_TEAM_FIXTURE_LIST';

export const LOADING_SQUAD_FOR_MANAGER_ID = 'LOADING_SQUAD_FOR_MANAGER_ID';
export const ADD_SQUAD_FOR_MANAGER_ID = 'ADD_SQUAD_FOR_MANAGER_ID';

export const LOADING_MANAGER_CURR_SEASON = 'LOADING_MANAGER_CURR_SEASON';
export const ADD_MANAGER_CURR_SEASON = 'ADD_MANAGER_CURR_SEASON';

export const LOADING_PLAYER_SEASON_STATS = 'LOADING_PLAYER_SEASON_STATS';
export const ADD_PLAYER_SEASON_STATS = 'ADD_PLAYER_SEASON_STATS';

export const LOADING_PLAYER_GW_STATS = 'LOADING_PLAYER_GW_STATS';
export const ADD_PLAYER_GW_STATS = 'ADD_PLAYER_GW_STATS';

export const LOADING_LEAGUE_INFO = 'LOADING_LEAGUE_INFO';
export const ADD_LEAGUE_INFO = 'ADD_LEAGUE_INFO';

export const LOADING_LEAGUE_POINTS_FOR_GW = 'LOADING_LEAGUE_POINTS_FOR_GW';
export const ADD_LEAGUE_POINTS_FOR_GW = 'ADD_LEAGUE_POINTS_FOR_GW';

export const LOADING_LIVE_DATA = 'LOADING_LIVE_DATA';
export const ADD_LIVE_DATA = 'ADD_LIVE_DATA';

export const LOADING_SQUADS_FOR_LEAGUE_ID = 'LOADING_SQUADS_FOR_LEAGUE_ID';
export const ADD_SQUADS_FOR_LEAGUE_ID = 'ADD_SQUADS_FOR_LEAGUE_ID';

export const LOADING_CURR_GW = 'LOADING_CURR_GW';
export const ADD_CURR_GW = 'ADD_CURR_GW';

export const TOGGLE_SHOW_PLAYERS_FORM = 'TOGGLE_SHOW_PLAYERS_FORM';

export const SET_SHOW_PLAYERS_FORM_VAL = 'SET_SHOW_PLAYERS_FORM_VAL';

